var User = require('./user');
var Like = require('./like');
var Match = require('./match');
var Chat = require('./chat');
var Picture = require('./picture');
var Reset = require('./reset');
var Confirmation = require('./confirmation');
var Invite = require('./invite');
// var Comment = require('./comment');
